### ISSUE TITLE
Find and Document Scoring Script for ImageNet Classification

### ISSUE THREAD

**Issue by danielnapierski** [isi-vista/unified-io-inference#16]
Find Scoring Script for ImageNet Classification
 * Document github repo where scoring script exists
 * Show how to use it on a saga-cluster node (with or without docker)
 * Add a demo script to this repo that can score a sample result from classification

**Comment by yash-reddy** [comment]
@danielnapierski   - The PR for the scoring script is now up for review at https://github.com/isi-vista/unified-io-inference/pull/19
